### ISSUE TITLE
[BUG] Nav bar absent in mobile view 

### ISSUE THREAD

**Issue by pri1311** [margaritahumanitarian/helpafamily#214] opened 2021-10-01 06:03 UTC
Navbar is absent for mobile view

**Steps to reproduce**
Open website on a mobile or a smaller screen (iPad)

**What did you expect to happen?**
Navigation in mobile view for ease of navigation.

**Comment by RedFox0x20** [comment] 2021-10-01 22:25
Please provide screenshots of this behaviour, I am unable to replicate this issue.

((Self assigned))

**Comment by ozer619** [comment] 2021-10-02 17:33
![Screenshot from 2021-10-02 22-50-11](https://user-images.githubusercontent.com/51698593/135726406-ecdd877b-a507-408d-8dd8-b7a4e01a478f.png)

@RedFox0x20 I found this bug too the navbar is not visible after some resolutions around 632x761

**Comment by RedFox0x20** [comment] 2021-10-02 17:40
After discussion in discord we have recognised that the issue is simply an issue of expected vs implemented behaviours.

Expected behaviour was some form of menu such as a burger menu, however this has not been implemented yet.

Suggested action:
Close this issue and create a new issue to discuss different menu types which could be used on smaller devices to maintain all navbar functionality.

**Comment by akshitarora921** [comment] 2021-10-03 11:43
Can I work on this? I will build a basic hamburger menu and then we can iterate over that.

**Comment by audreyfeldroy** [comment] 2021-10-03 17:12
Sure @akshitarora921! Since I see suggestions/votes to close this issue and start anew, I'd say the first step is to create an issue if you need help figuring out the strategy, or a PR as proposal if you want to start with code demonstrating your idea. 

I'll be around in [our Discord server](https://discord.gg/aGuWx7QE) for the next hour or so if anyone needs help 🙂

**Closed as completed** 2021-10-07 16:57 UTC
Labels: bug
